name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: Spectroscopy.tex
      - name: LaTeX Action
        # You may pin to the exact commit or the version.
        # uses: fudan-mse/latex-action@eb2eb7ba472011213ac0a6286fd776494623362c
        uses: fudan-mse/latex-action@v0.0.1
        with:
          # The root LaTeX file to be compiled
          root_file: Spectroscopy.tex
          # The working directory for the LaTeX engine
          working_directory: .
          # The LaTeX engine to be invoked
          compiler: pdflatex
          # Extra arguments to be passed to the LaTeX engine
          args: -pdf -file-line-error -interaction=nonstopmode -o document.pdf
          # Install extra packages by tlmgr
          # extra_packages: # optional
          # Install extra packages by apk
          # extra_system_packages: # optional
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: document.pdf
      
