name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: LaTeX compilation
      # You may pin to the exact commit or the version.
      # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
      uses: dante-ev/latex-action@2021-A
      with:
        # The root LaTeX file to be compiled
        root_file: Spectroscopy.tex
        # The working directory for the latex compiler to be invoked
        working_directory: . # optional
        # LaTeX engine to be used
        compiler: pdflatex # optional, default is latexmk
        # Extra arguments to be passed to the latex compiler
        # args: -pdf -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
        # Install extra packages by apt-get
        # extra_system_packages: # optional
